### ISSUE TITLE
Broken interface color scheme for Intellij IDEA Community Edition

### ISSUE THREAD

**Issue by GeneralTao2** [Hiberbee/code-highlight-themes#99]
**Describe the bug**
The plugin doesn't change main interface color scheme of the Intellij IDEA Community Edition (leaves it as default)

**To Reproduce**
1. Install from JetBrains Toolbox IntelliJ IDEA 2023.1.1 Build #IC-231.8770.65, built on April 27, 2023
2. Install Hiberbee plugin with 2023.3.30.121using browser button
3. Restart Intellij 
4. See the broken color scheme

**Expected behavior**
See fine color scheme as in main readme page of this repo

**Screenshots**
![image](https://user-images.githubusercontent.com/42372666/235355341-ac2cb97d-8019-4e4b-b302-429085b1b8cb.png)

**Desktop (please complete the following information):**
 - IntelliJ IDEA 2023.1.1 (Community Edition)
   Runtime version: 17.0.6+10-b829.9 amd64
   VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
- OS: Microsoft Windows 10 Home 10.0.19045 Build 19045

**Additional context**
First I've noticed the issue after update IntelliJ IDEA 2021 to IntelliJ IDEA 2021.2.4 along with the plugin. I've tried to invalidate cache with all options selected for Intellij and reinstall the plugin - didn't help. Then I downloaded the 2023 version and faced the same issue

UPD:
So far I use Hiberbee version 2022.5.16.1805, works with IntelliJ IDEA 2023.1.1 (Community Edition). Almost all newer versions cause the issue for me. Is this a redesign? If yes, then why? Like it used to be 
![image](https://user-images.githubusercontent.com/42372666/235477736-059c22a4-eef7-4af9-a464-04fd7a7c7cb0.png)

**Comment by vladyslavvolkov** [comment]
Hi @GeneralTao2, yep, in 2023+ versions (or technically 231.* builds) Jetbrains presented new UI, which affected lots of compatibility breaks. For releases done staring 2023 I've set `since-build` 231.*, meaning end of support old versions. Most likely I've configured incorrect since-until attributes for latest available for you version. 

Going to install old version and make sure latest plugin version is compatible with it. Most likely that will drop in separate branch in this repo. 

Thanks for feedback, sorry for messing around
